### ISSUE TITLE
Ordering A VK

### ISSUE THREAD

**Issue by christianman** [jackbo11/cm1101_team13_game#1]
When you go to Bar2 and after that "get A VK" it throws an error. Its only for that drink.

**Comment by rexpoon** [comment]
Traceback (most recent call last):
  File "C:\Users\c1667859\Desktop\cm1101_team13_game\game.py", line 523, in <module>
    main()
  File "C:\Users\c1667859\Desktop\cm1101_team13_game\game.py", line 501, in main
    execute_command(command)
  File "C:\Users\c1667859\Desktop\cm1101_team13_game\game.py", line 392, in execute_command
    execute_get(command[1], player1, player1.current_room)
  File "C:\Users\c1667859\Desktop\cm1101_team13_game\game.py", line 289, in execute_get
    apply_consumable_effect_by_id(consumable, player, room)
  File "C:\Users\c1667859\Desktop\cm1101_team13_game\game.py", line 87, in apply_consumable_effect_by_id
    apply_consumable_effect([item for item in room["consumables"] if item.get('id') == consumable][0], player)
IndexError: list index out of range
